# Generated by Django 3.2.9 on 2022-11-05 07:55

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='nationality',
            field=django_countries.fields.CountryField(default='KE', max_length=57, verbose_name='Country'),
        ),
    ]
