# Generated by Django 3.2.9 on 2022-11-05 07:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_alter_appointments_appointment_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='appointment_time',
            field=models.TimeField(default=datetime.time(13, 23, 24, 311458), verbose_name='appointment time'),
        ),
    ]
