# Generated by Django 2.2.28 on 2022-11-09 08:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0010_auto_20221107_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='appointment_time',
            field=models.TimeField(default=datetime.time(14, 2, 16, 626112), verbose_name='appointment time'),
        ),
    ]
