# Generated by Django 2.2.16 on 2022-11-13 21:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0011_auto_20221109_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='appointment_time',
            field=models.TimeField(default=datetime.time(3, 4, 49, 629989), verbose_name='appointment time'),
        ),
    ]
