# Generated by Django 2.2.16 on 2022-11-13 21:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0012_auto_20221114_0304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='appointment_time',
            field=models.TimeField(default=datetime.time(3, 10, 26, 433428), verbose_name='appointment time'),
        ),
    ]
