# Generated by Django 3.2.16 on 2022-11-14 05:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0014_auto_20221114_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='appointment_time',
            field=models.TimeField(default=datetime.time(11, 26, 56, 39182), verbose_name='appointment time'),
        ),
    ]
