# Generated by Django 3.2.16 on 2022-11-14 05:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0015_alter_appointments_appointment_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='appointment_time',
            field=models.TimeField(default=datetime.time(11, 28, 26, 16189), verbose_name='appointment time'),
        ),
    ]
