# Generated by Django 2.2.13 on 2022-11-16 00:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0020_auto_20221116_0547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='appointment_time',
            field=models.TimeField(default=datetime.time(6, 15, 41, 656145), verbose_name='appointment time'),
        ),
        migrations.AlterField(
            model_name='medication',
            name='price',
            field=models.FloatField(null=True, verbose_name='price'),
        ),
    ]
