# Generated by Django 2.2.13 on 2022-11-16 01:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0021_auto_20221116_0615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='appointment_time',
            field=models.TimeField(default=datetime.time(6, 40, 27, 507782), verbose_name='appointment time'),
        ),
        migrations.AlterField(
            model_name='test',
            name='price',
            field=models.FloatField(null=True, verbose_name='price'),
        ),
    ]
